cmake_minimum_required(VERSION 3.20)


add_subdirectory(CoreBasicUsage)
add_subdirectory(CommonBasicUsage)
add_subdirectory(AppCoreBasicUsage)
add_subdirectory(AppParameterBasicUsage)
add_subdirectory(AppParametersPageBasicUsage)
add_subdirectory(AppParametersPageBenchmark)
add_subdirectory(JsonTxt2JsonBasicUsage)
add_subdirectory(JsonYamlToJsonTestSuite)

