#ifndef QTNOIDCOMMON_GLOBAL_H
#define QTNOIDCOMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QTNOIDCOMMON_LIBRARY
#  define QTNOIDCOMMON_EXPORT Q_DECL_EXPORT
#else
#  define QTNOIDCOMMON_EXPORT Q_DECL_IMPORT
#endif

#endif // QTNOIDCOMMON_GLOBAL_H